name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{github.repository}}
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v3
      # docker buildx is used to build multi-platform images with Dockerfile
      - name: Set up Docker Buildx
        run: |
          docker buildx -f Dockerfile . --platform linux/amd64 -t ghcr.io/${{github.repository}}:${{github.sha}} -t ghcr.io/${{github.repository}}:latest
      

     